name: Service Container Example - Full Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    # Ana container: Uygulamayı çalıştırır
    container:
      image: node:18-alpine
      ports:
        - 3000:3000
      env:
        NODE_ENV: test
        LOG_LEVEL: debug
    
    # Destekleyici servisler: Tüm job boyunca çalışır
    services:
      # ====== PostgreSQL ======
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: app_password123
          POSTGRES_DB: app_testdb
          POSTGRES_INITDB_ARGS: "--encoding=UTF8"
        
        # Health check: Container'ın hazır olup olmadığını kontrol eder
        options: |
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
        
        ports:
          - 5432:5432
      
      # ====== Redis ======
      redis:
        image: redis:7-alpine
        options: |
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
          --health-start-period 5s
        ports:
          - 6379:6379
      
      # ====== MongoDB ======
      mongodb:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo_admin
          MONGO_INITDB_ROOT_PASSWORD: mongo_password123
          MONGO_INITDB_DATABASE: app_mongodb
        options: |
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
        ports:
          - 27017:27017
      
      # ====== Elasticsearch ======
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        options: |
          --health-cmd "curl -f http://localhost:9200 > /dev/null"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 15s
        ports:
          - 9200:9200
      
      # ====== RabbitMQ ======
      rabbitmq:
        image: rabbitmq:3.12-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: |
          --health-cmd "rabbitmq-diagnostics ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
        ports:
          - 5672:5672
          - 15672:15672
      
      # ====== MinIO (S3-compatible) ======
      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: miniopassword123
        options: |
          --health-cmd "curl -f http://localhost:9000/minio/health/live > /dev/null"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 9000:9000
    
    steps:
      # ====== HAZIRLIK ======
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display environment info
        run: |
          echo "=== Environment Information ==="
          echo "Node: $(node --version)"
          echo "npm: $(npm --version)"
          echo "Container: Running inside Node 18-Alpine"
          echo ""
      
      # ====== SERVIS KONTROLÜNÜm ETME ======
      - name: Wait for services to be ready
        run: |
          echo "=== Checking Service Health ==="
          
          # PostgreSQL
          echo "⏳ Checking PostgreSQL..."
          for i in {1..30}; do
            if pg_isready -h postgres -p 5432 -U app_user >/dev/null 2>&1; then
              echo "✓ PostgreSQL is ready"
              break
            fi
            echo "  Attempt $i: PostgreSQL not ready yet..."
            sleep 2
          done
          
          # Redis
          echo "⏳ Checking Redis..."
          for i in {1..15}; do
            if redis-cli -h redis -p 6379 ping 2>/dev/null | grep -q PONG; then
              echo "✓ Redis is ready"
              break
            fi
            echo "  Attempt $i: Redis not ready yet..."
            sleep 1
          done
          
          # MongoDB
          echo "⏳ Checking MongoDB..."
          for i in {1..30}; do
            if nc -z mongodb 27017 2>/dev/null; then
              echo "✓ MongoDB is ready"
              break
            fi
            echo "  Attempt $i: MongoDB not ready yet..."
            sleep 2
          done
          
          # Elasticsearch
          echo "⏳ Checking Elasticsearch..."
          for i in {1..30}; do
            if curl -s http://elasticsearch:9200 | grep -q "You Know, for Search"; then
              echo "✓ Elasticsearch is ready"
              break
            fi
            echo "  Attempt $i: Elasticsearch not ready yet..."
            sleep 2
          done
          
          # RabbitMQ
          echo "⏳ Checking RabbitMQ..."
          for i in {1..30}; do
            if nc -z rabbitmq 5672 2>/dev/null; then
              echo "✓ RabbitMQ is ready"
              break
            fi
            echo "  Attempt $i: RabbitMQ not ready yet..."
            sleep 2
          done
          
          # MinIO
          echo "⏳ Checking MinIO..."
          for i in {1..15}; do
            if nc -z minio 9000 2>/dev/null; then
              echo "✓ MinIO is ready"
              break
            fi
            echo "  Attempt $i: MinIO not ready yet..."
            sleep 1
          done
          
          echo ""
          echo "=== All Services Ready ==="
      
      # ====== BAĞIMLILIKLARINI KURMA ======
      - name: Install dependencies
        run: |
          echo "Installing npm packages..."
          npm ci
      
      # ====== VERITABANI SETUP ======
      - name: Setup PostgreSQL database
        run: |
          echo "Setting up PostgreSQL schema..."
          psql -h postgres -U app_user -d app_testdb -c "
            CREATE TABLE IF NOT EXISTS users (
              id SERIAL PRIMARY KEY,
              name VARCHAR(100),
              email VARCHAR(100) UNIQUE,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
            
            CREATE TABLE IF NOT EXISTS posts (
              id SERIAL PRIMARY KEY,
              user_id INTEGER REFERENCES users(id),
              title VARCHAR(200),
              content TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
          " || echo "Database schema already exists"
        env:
          PGPASSWORD: app_password123
      
      # ====== TESTLER ======
      - name: Run unit tests
        run: npm run test:unit -- --passWithNoTests
      
      - name: Run integration tests
        run: npm run test:integration -- --passWithNoTests || true
        env:
          # PostgreSQL
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_NAME: app_testdb
          DATABASE_USER: app_user
          DATABASE_PASSWORD: app_password123
          DATABASE_URL: postgresql://app_user:app_password123@postgres:5432/app_testdb
          
          # Redis
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_URL: redis://redis:6379/0
          
          # MongoDB
          MONGODB_URL: mongodb://mongo_admin:mongo_password123@mongodb:27017/app_mongodb
          
          # Elasticsearch
          ELASTICSEARCH_URL: http://elasticsearch:9200
          
          # RabbitMQ
          RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
          
          # MinIO
          MINIO_ENDPOINT: http://minio:9000
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: miniopassword123
      
      - name: Run database tests
        run: |
          echo "Testing PostgreSQL connection..."
          psql -h postgres -U app_user -d app_testdb -c "SELECT COUNT(*) FROM users;" || echo "Query failed"
        env:
          PGPASSWORD: app_password123
      
      - name: Verify Redis connection
        run: |
          echo "Testing Redis connection..."
          redis-cli -h redis -p 6379 SET test_key "Hello from GitHub Actions" || echo "Redis set failed"
          redis-cli -h redis -p 6379 GET test_key || echo "Redis get failed"
      
      - name: Check Elasticsearch cluster
        run: |
          echo "Checking Elasticsearch cluster health..."
          curl -s http://elasticsearch:9200/_cluster/health | head -c 100
      
      - name: Build application
        run: npm run build 2>/dev/null || echo "Build script not configured"
      
      # ====== RAPOR VE ARTIFACTS ======
      - name: Generate test report
        if: always()
        run: |
          echo "=== Integration Test Summary ===" > test-report.txt
          echo "Date: $(date)" >> test-report.txt
          echo "Services Used:" >> test-report.txt
          echo "  - PostgreSQL 15-Alpine" >> test-report.txt
          echo "  - Redis 7-Alpine" >> test-report.txt
          echo "  - MongoDB 6" >> test-report.txt
          echo "  - Elasticsearch 8.5.0" >> test-report.txt
          echo "  - RabbitMQ 3.12" >> test-report.txt
          echo "  - MinIO Latest" >> test-report.txt
          echo "" >> test-report.txt
          echo "All services are ephemeral and will be removed after test completion" >> test-report.txt
      
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-report.txt
      
      - name: Job completion status
        if: always()
        run: |
          echo "=== Job Status ==="
          echo "Status: ${{ job.status }}"
          echo "All service containers will be automatically stopped and removed"
          echo "Next workflow run will start with fresh containers"
